version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - ":game_die: dependencies"
      - ":robot: bot"
    allowed_updates:
      - match:
          update_type: "all"
    automerged_updates:
      - match:
          dependency_type: "all"
          update_type: "semver:minor"
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    allowed_updates:
      - match:
          update_type: "all"
    automerged_updates:
      - match:
          dependency_type: "all"
          update_type: "semver:minor"
    labels:
      - ":game_die: dependencies"
      - ":robot: bot"
