#!/usr/bin/env node

const fs = require('fs')
const path = require('path')
const matter = require('gray-matter')

const calculateNewName = data => {
  let simpleSlug = data.slug.replace(/^\/+|\/+$/g, '')
  let date = new Date(data.date)
  return path.join(`p-${simpleSlug}`, `entry${date.getTime()}.md`)
}

const mkdirP = dir => {
  if (!fs.existsSync(dir)) {
    console.log(`mkdir: ${dir}`)
    fs.mkdirSync(dir, 0o755)
  }
}

const topDir = path.resolve(__dirname, 'comments')

fs
  .readdirSync(topDir)
  .filter(name => {
    return fs.statSync(path.join(topDir, name)).isFile()
  })
  .map(name => {
    let oldPath = path.join(topDir, name)
    let comment = matter(fs.readFileSync(oldPath, 'utf8'))
    let newPath = path.join(topDir, calculateNewName(comment.data))
    let newDir = path.dirname(newPath)

    mkdirP(newDir)
    console.log(`mv: ${oldPath} -> ${newPath}`)
    fs.renameSync(oldPath, newPath)
  })
