#!/bin/bash

set -eEuo pipefail

build_date="$(env TZ='America/New_York' date '+%Y-%m-%dT%H:%M:%SZ')"
top_dir="$(git rev-parse --show-toplevel)"
repo_url="$(git ls-remote --get-url)"
branch="$(git rev-parse --abbrev-ref HEAD)"
version=$(cat "${top_dir}/.node-version")
tag=${IMAGE_NAME:-docwhat:local}
gitsha=${GIT_SHA1:-$(git rev-parse HEAD)}
gitcommit=${GIT_COMMIT:-$(git log -1 --date=short --format='%h %ad %s')}

declare -r \
  build_date \
  top_dir \
  repo_url \
  branch \
  version \
  tag \
  gitsha \
  gitcommit

cat <<INFO
On ${build_date}
We're building the image ${tag} with Node ${version}
From ${repo_url}#${branch} (${gitsha})
===========================================================
INFO

declare -ra docker_build_args=(
  "--build-arg=NODE_VERSION=${version}"
  "--build-arg=SITE_COMMIT=${gitcommit}"
  "--build-arg=SITE_VERSION=${gitsha}"
  "--target=final"
  "--tag=${tag}"
  "--pull"
  "--label=org.label-schema.vcs-ref=${gitsha}"
  "--label=org.label-schema.vcs-url=${repo_url}"
  "--label=org.label-schema.build-date=${build_date}"
  "${top_dir}"
)

exec docker build "${docker_build_args[@]}"

# EOF
