#!/bin/bash

set -eEuo pipefail

top_dir="$(git rev-parse --show-toplevel)"
declare -r top_dir

tag="${IMAGE_NAME:-docwhat:local}"
declare -r tag

node_version=$(cat "${top_dir}/.node-version")
declare -r node_version

build_date="$(env TZ='America/New_York' date '+%Y-%m-%dT%H:%M:%SZ')"
declare -r build_date

git_url="$(git ls-remote --get-url)"
git_branch="$(git rev-parse --abbrev-ref HEAD)"
git_sha=${GIT_SHA1:-$(git rev-parse HEAD)}
git_commit=${GIT_COMMIT:-$(git log -1 --date=short --format='%h %ad %s')}
declare -r git_url git_branch git_sha git_commit

cat <<INFO
On ${build_date}
We're building the image ${tag} with Node ${node_version}
From ${git_url}#${git_branch} (${git_sha})
===========================================================
INFO

declare -ra docker_build_args=(
  "--build-arg=NODE_VERSION=${node_version}"
  "--build-arg=SITE_COMMIT=${git_commit}"
  "--build-arg=SITE_VERSION=${git_sha}"
  "--platform=linux/amd64"
  "--target=final"
  "--tag=${tag}"
  "--pull"
  "${top_dir}"
)

exec docker build "${docker_build_args[@]}"

# EOF
