#!/bin/bash

set -eEuo pipefail

cd "$(dirname "$(dirname "$0")")"

# Fallback if running in Alpine (e.g., github actions)
if ! command -v pigz >/dev/null 2>&1; then
  if [[ -x /sbin/apk ]]; then
    apk --no-cache add pigz
  else
    echo "Unable to find compressor 'pigz'" 1>&2
    exit 10
  fi
fi

find public -type f \
  -iname '*.gz' \
  -print0 |
  xargs -0 rm -f

find public -type f \
  \( \
  -name '*.css' -o \
  -name '*.html' -o \
  -name '*.js' -o \
  -name '*.json' -o \
  -name '*.map' -o \
  -name '*.svg' -o \
  -name '*.txt' -o \
  -name '*.xml' \
  \) -print0 |
  xargs -0 pigz --keep

# EOF
