#!/bin/bash

set -eEuo pipefail

declare -r tag=${IMAGE_NAME:-docwhat:local}
declare -r push_tag=${1:-${tag}}

function docker_username() {
  local oldstate
  if [[ -n ${DOCKER_USERNAME:-} ]]; then
    echo "$DOCKER_USERNAME"
  else
    lpass show --username --sync=auto docker.com
  fi
}

function docker_password() {
  local -r oldstate="$(shopt -po xtrace)"
  set +x

  if [[ -n ${DOCKER_PASSWORD:-} ]]; then
    echo "$DOCKER_PASSWORD"
  else
    lpass show --password --sync=auto docker.com
  fi
  eval "$oldstate" 1>&2
}

if [[ $tag != "$push_tag" ]]; then
  docker tag "$tag" "$push_tag"
fi

if ! docker push "$push_tag"; then
  username=$(docker_username)
  declare -r username

  docker_password | docker login --username="$username" --password-stdin

  docker push "$push_tag"
fi

if [[ -n ${CI:-} ]]; then
  curl -X POST -sSf 'https://hooks.microbadger.com/images/docwhat/docwhat/abVd1cbH3B2206gjokNJ7jZuxEM='
fi

# EOF
