#!/bin/bash

set -eEuo pipefail

top_dir="$(git rev-parse --show-toplevel)"
declare -r top_dir

function push_tag() {
  local -r push_tag="docwhat/docwhat:${1}"
  local -r tag=${IMAGE_NAME:-docwhat:local}

  if [[ $tag != "$push_tag" ]]; then
    docker tag "$tag" "$push_tag"
  fi

  if ! docker push "$push_tag"; then
    docker push "$push_tag"
  fi
}

## Main

"${top_dir}/script/login"

for tag in "$@"; do
  push_tag "$tag"
done

if [[ -n ${CI:-} ]]; then
  curl -X POST -sSf 'https://hooks.microbadger.com/images/docwhat/docwhat/abVd1cbH3B2206gjokNJ7jZuxEM='
fi

# EOF
