#!/bin/bash

set -eEuo pipefail

declare -r \
  tag=${IMAGE_NAME:-docwhat:local} \
  push_tag=${1:-${tag}}

if [[ $tag != "$push_tag" ]]; then
  docker tag "$tag" "$push_tag"
fi

if ! docker push "$tag"; then
  username=${DOCKER_USERNAME:-docwhat}
  password=${DOCKER_PASSWORD:-$(lpass show --password docker.com)}
  declare -r username password

  echo "$password" | docker login -u "$username" --password-stdin

  exec docker push "$tag"
fi

# EOF
