name: Auto-merge Dependabot PRs
on:
  schedule:
    - cron: "23 */6 * * *"
jobs:
  auto_merge:
    name: Auto-merge Dependabot PRs
    runs-on: ubuntu-latest
    steps:
      - uses: akheron/dependabot-cron-action@b44d8e19e4f49eede254d9884e3f0e7712d431ba
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          merge-method: "squash"
