name: CI

on:
  pull_request:
    branches:
      - master
      - main
  push:
    branches:
      - master
      - main
    paths:
      - '.github/workflows/ci.yml'
      - '.github/workflows/ci.yaml'
      - '!.github/**'
      - '!.vscode/**'
      - '!.devcontainer/**'

jobs:
  build:
    name: Build Container
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1.6.0

      - name: Cache Docker layers
        uses: actions/cache@v2.1.6
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1.10.0
        if: github.event_name != 'pull_request'
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v2

      - name: Prepare
        id: prep
        env:
          docker_image: 'ghcr.io/${{ github.repository_owner }}/blog'
        run: ./script/ci-prep.bash

      - name: Build and push
        uses: docker/build-push-action@v2.7.0
        with:
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.prep.outputs.tags }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          target: final
          build-args: |
            NODE_VERSION=${{ steps.prep.outputs.node_version }}
            SITE_COMMIT=${{ steps.prep.outputs.commit }}
            SITE_VERSION=${{ github.sha }}
          labels: |
            org.opencontainers.image.created=${{ steps.prep.outputs.now }}
            org.opencontainers.image.source=${{ github.repositoryUrl }}
            org.opencontainers.image.revision=${{ github.sha }}
      - name: Trigger hive update
        env:
          GITHUB_TOKEN: ${{ secrets.GHCR_TOKEN }}
        run: |
          gh api \
            repos/holtje/hive-config/actions/workflows/3279287/dispatches \
            --field=ref=main
