name: Check Markdown links

on:
  push:
    branches:
      - master
      - main
    paths:
      - "content/posts/**.md"
      - "content/pi/**.md"
      - "README.md"
  pull_request:
    branches:
      - master
      - main
    paths:
      - "content/posts/**.md"
      - "content/pi/**.md"
      - "README.md"
  schedule:
    # https://crontab.guru/every-quarter
    - cron: "0 0 1 */3 *"

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          use-quiet-mode: "yes"
          use-verbose-mode: "yes"
          check-modified-files-only: "yes"
          folder-path: "content/posts,content/pi"
          file-path: "./README.md"
